import type { Conversation, Message } from "./types";

export const currentUserId = "me";

const avatar = (seed: string) => `https://i.pravatar.cc/150?u=${seed}`;

export const mockConversations: Conversation[] = [
    {
        id: "conv-1",
        name: "Trekking Buddies",
        isGroup: true,
        memberAvatars: [avatar("sarita"), avatar("bibek"), avatar("anish"), avatar("maya")],
        lastMessage: "Sarita: Let's leave by 6 AM tomorrow",
        lastMessageTime: "9:10 AM",
        lastMessageIsOwn: false,
        unreadCount: 3,
        pinned: true,
        online: true,
        typing: true,
    },
    {
        id: "conv-2",
        name: "Sarita Gurung",
        avatar: avatar("sarita"),
        isGroup: false,
        lastMessage: "Sounds perfect, see you then!",
        lastMessageTime: "10:05 AM",
        lastMessageIsOwn: true,
        lastMessageStatus: "read",
        unreadCount: 0,
        pinned: true,
        online: true,
        typing: false,
    },
    {
        id: "conv-3",
        name: "Bibek Shrestha",
        avatar: avatar("bibek"),
        isGroup: false,
        lastMessage: "Can you review the PR when free?",
        lastMessageTime: "8:30 AM",
        lastMessageIsOwn: false,
        unreadCount: 2,
        pinned: false,
        online: false,
        typing: false,
    },
    {
        id: "conv-4",
        name: "Design Team",
        isGroup: true,
        memberAvatars: [avatar("maya"), avatar("rajesh"), avatar("prakash")],
        lastMessage: "Sent the updated mockups",
        lastMessageTime: "Yesterday",
        lastMessageIsOwn: true,
        lastMessageStatus: "delivered",
        unreadCount: 0,
        pinned: false,
        online: true,
        typing: false,
    },
    {
        id: "conv-5",
        name: "Anish Koirala",
        avatar: avatar("anish"),
        isGroup: false,
        lastMessage: "Call me when you're free",
        lastMessageTime: "Yesterday",
        lastMessageIsOwn: false,
        unreadCount: 1,
        pinned: false,
        online: true,
        typing: false,
    },
    {
        id: "conv-6",
        name: "Maya Tamang",
        avatar: avatar("maya"),
        isGroup: false,
        lastMessage: "Thank you so much 🙏",
        lastMessageTime: "Yesterday",
        lastMessageIsOwn: false,
        unreadCount: 0,
        pinned: false,
        online: false,
        typing: false,
    },
    {
        id: "conv-7",
        name: "Rajesh Karki",
        avatar: avatar("rajesh"),
        isGroup: false,
        lastMessage: "Ok will call you",
        lastMessageTime: "Monday",
        lastMessageIsOwn: true,
        lastMessageStatus: "sent",
        unreadCount: 0,
        pinned: false,
        online: false,
        typing: false,
    },
    {
        id: "conv-8",
        name: "College Group",
        isGroup: true,
        memberAvatars: [avatar("prakash"), avatar("sarita"), avatar("bibek"), avatar("anish"), avatar("maya")],
        lastMessage: "Prakash: check the link",
        lastMessageTime: "Monday",
        lastMessageIsOwn: false,
        unreadCount: 5,
        pinned: false,
        online: true,
        typing: false,
    },
];

export const mockMessagesByConversation: Record<string, Message[]> = {
    "conv-1": [
        {
            id: "conv-1-msg-1",
            conversationId: "conv-1",
            senderId: "sarita",
            senderName: "Sarita Gurung",
            senderAvatar: avatar("sarita"),
            content: "Guys, are we still on for the trek next weekend?",
            timestamp: "9:00 AM",
            isOwn: false,
        },
        {
            id: "conv-1-msg-2",
            conversationId: "conv-1",
            senderId: "bibek",
            senderName: "Bibek Shrestha",
            senderAvatar: avatar("bibek"),
            content: "Yes! I already packed my bag 😄",
            timestamp: "9:02 AM",
            isOwn: false,
        },
        {
            id: "conv-1-msg-3",
            conversationId: "conv-1",
            senderId: currentUserId,
            senderName: "You",
            content: "Count me in too!",
            timestamp: "9:05 AM",
            isOwn: true,
            status: "read",
        },
        {
            id: "conv-1-msg-4",
            conversationId: "conv-1",
            senderId: "sarita",
            senderName: "Sarita Gurung",
            senderAvatar: avatar("sarita"),
            content: "@Bibek can you bring the tent this time?",
            timestamp: "9:06 AM",
            isOwn: false,
            mention: "@Bibek",
        },
        {
            id: "conv-1-msg-5",
            conversationId: "conv-1",
            senderId: "bibek",
            senderName: "Bibek Shrestha",
            senderAvatar: avatar("bibek"),
            content: "Sure, here's the trail map for reference: trail map",
            timestamp: "9:08 AM",
            isOwn: false,
            link: { label: "trail map", url: "https://maps.example.com/annapurna-trail" },
        },
        {
            id: "conv-1-msg-6",
            conversationId: "conv-1",
            senderId: "sarita",
            senderName: "Sarita Gurung",
            senderAvatar: avatar("sarita"),
            content: "Let's leave by 6 AM tomorrow",
            timestamp: "9:10 AM",
            isOwn: false,
        },
    ],
    "conv-2": [
        {
            id: "conv-2-msg-1",
            conversationId: "conv-2",
            senderId: "sarita",
            senderName: "Sarita Gurung",
            senderAvatar: avatar("sarita"),
            content: "Hey, are you free this weekend?",
            timestamp: "10:00 AM",
            isOwn: false,
        },
        {
            id: "conv-2-msg-2",
            conversationId: "conv-2",
            senderId: currentUserId,
            senderName: "You",
            content: "Yeah I think so, what's up?",
            timestamp: "10:02 AM",
            isOwn: true,
            status: "read",
        },
        {
            id: "conv-2-msg-3",
            conversationId: "conv-2",
            senderId: "sarita",
            senderName: "Sarita Gurung",
            senderAvatar: avatar("sarita"),
            content: "Want to join the trek group",
            timestamp: "10:03 AM",
            isOwn: false,
        },
        {
            id: "conv-2-msg-4",
            conversationId: "conv-2",
            senderId: currentUserId,
            senderName: "You",
            content: "Sounds perfect, see you then!",
            timestamp: "10:05 AM",
            isOwn: true,
            status: "read",
        },
    ],
    "conv-3": [
        {
            id: "conv-3-msg-1",
            conversationId: "conv-3",
            senderId: "bibek",
            senderName: "Bibek Shrestha",
            senderAvatar: avatar("bibek"),
            content: "Can you review the PR when free?",
            timestamp: "8:30 AM",
            isOwn: false,
        },
        {
            id: "conv-3-msg-2",
            conversationId: "conv-3",
            senderId: currentUserId,
            senderName: "You",
            content: "On it, give me 10 mins",
            timestamp: "8:31 AM",
            isOwn: true,
            status: "sent",
        },
    ],
    "conv-4": [
        {
            id: "conv-4-msg-1",
            conversationId: "conv-4",
            senderId: "maya",
            senderName: "Maya Tamang",
            senderAvatar: avatar("maya"),
            content: "Working on the new mockups",
            timestamp: "Yesterday",
            isOwn: false,
        },
        {
            id: "conv-4-msg-2",
            conversationId: "conv-4",
            senderId: currentUserId,
            senderName: "You",
            content: "Sent the updated mockups",
            timestamp: "Yesterday",
            isOwn: true,
            status: "delivered",
        },
    ],
    "conv-5": [
        {
            id: "conv-5-msg-1",
            conversationId: "conv-5",
            senderId: "anish",
            senderName: "Anish Koirala",
            senderAvatar: avatar("anish"),
            content: "Call me when you're free",
            timestamp: "Yesterday",
            isOwn: false,
        },
    ],
    "conv-6": [
        {
            id: "conv-6-msg-1",
            conversationId: "conv-6",
            senderId: "maya",
            senderName: "Maya Tamang",
            senderAvatar: avatar("maya"),
            content: "Thank you so much 🙏",
            timestamp: "Yesterday",
            isOwn: false,
        },
    ],
    "conv-7": [
        {
            id: "conv-7-msg-1",
            conversationId: "conv-7",
            senderId: currentUserId,
            senderName: "You",
            content: "Ok will call you",
            timestamp: "Monday",
            isOwn: true,
            status: "sent",
        },
    ],
    "conv-8": [
        {
            id: "conv-8-msg-1",
            conversationId: "conv-8",
            senderId: "prakash",
            senderName: "Prakash Rai",
            senderAvatar: avatar("prakash"),
            content: "Check the link for the notes",
            timestamp: "Monday",
            isOwn: false,
            link: { label: "notes", url: "https://docs.example.com/college-notes" },
        },
    ],
};
